### PR TITLE
Switch to using Godot's High-Level Multiplayer API via the NakamaMultiplayerBridge

### PR DESCRIPTION
**Pull request by dsnopek**

### CODE REVIEW

**Comment by dsnopek** [comment]
The updated tutorial is live at https://heroiclabs.com/docs/nakama/tutorials/godot/fishgame/

So this is finally ready for review!

**Comment by lugehorsam** [comment]
@dsnopek looks good to me, though should the `addons` folder be in source control?

**Comment by dsnopek** [comment]
> should the addons folder be in source control?

There isn't really a better way to do it. We can't use a Git submodule because the paths would be wrong. Godot doesn't have a package manager to automatically pull dependencies in. I suppose we could write a script to download the version of the addon we want? That's not a standard practice or anything, though, folks generally expect to be able to checkout a game's source and have everything there they need to run the game.

**Comment by lugehorsam** [comment]
@dsnopek no worries -- didn't realize Godot didn't have a package manager. Agreed it's the best solution until then 👍

**Review by lugehorsam — APPROVED** [review]

**Pull request merged**
